name: Release 📦

on:
    push:
      tags:
        - 'v*.*.*'
      paths-ignore:
        - 'README.md'
        - '.vscode'
        - '.idea'
    pull_request:
      branches:
        - master
        - main
      paths-ignore:
        - 'README.md'
        - '.vscode'
        - '.idea'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Package Application
          uses: JackMcKew/pyinstaller-action-windows@main
          with:
              path: src
        - uses: actions/upload-artifact@v2
          with:
            name: name-of-artifact
            path: src/dist/windows