name: Release 📦

on:
    push:
      tags:
        - 'v*.*.*'
      paths-ignore:
        - 'README.md'
        - '.vscode'
        - '.idea'
    pull_request:
      branches:
        - master
        - main
      paths-ignore:
        - 'README.md'
        - '.vscode'
        - '.idea'

jobs:
  pyinstaller-build:
    name: Build and publish Python 🐍 distributions 📦
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.10'
          spec: 'smtk\smtk.spec'
          requirements: 'requirements.txt'
          options: --name "smtk"